# Generated by Django 5.2.17 on 2026-10-01 17:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0003_amenity_roomcategoryamenity_roomcategory_amenities_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(db_index=True, help_text='Start date of maintenance window (inclusive)')),
                ('end_date', models.DateField(db_index=True, help_text='End date of maintenance window (exclusive completion date)')),
                ('maintenance_type', models.CharField(choices=[('repair', 'Emergency Repair / Fixture Fix'), ('routine', 'Routine Maintenance / Inspection'), ('deep_clean', 'Deep Sanitization & Pest Control'), ('renovation', 'Upgrades & Physical Renovation')], db_index=True, default='repair', help_text='Classification of maintenance work', max_length=50)),
                ('reason', models.CharField(default='Maintenance Work', help_text='Short summary of the work required', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Work orders, vendor details, and physical damage notes')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Status toggle. Inactive blocks do not consume inventory')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff member who scheduled the maintenance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenance_blocks', to=settings.AUTH_USER_MODEL)),
                ('physical_room', models.ForeignKey(help_text='Target physical room undergoing maintenance', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_blocks', to='rooms.physicalroom')),
            ],
            options={
                'verbose_name': 'Maintenance Block',
                'verbose_name_plural': 'Maintenance Blocks',
                'ordering': ['-start_date', 'physical_room__room_number'],
                'indexes': [models.Index(fields=['physical_room', 'is_active', 'start_date', 'end_date'], name='inventory_m_physica_8c284b_idx'), models.Index(fields=['start_date', 'end_date', 'is_active'], name='inventory_m_start_d_67e79e_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoomBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(db_index=True, help_text='Start date of the block (inclusive)')),
                ('end_date', models.DateField(db_index=True, help_text='End date of the block (exclusive checkout date)')),
                ('reason', models.CharField(default='Operational Block', help_text='Reason for administrative block', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Internal staff notes and justification')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Status toggle. Inactive blocks do not consume inventory')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff member who created the block', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_room_blocks', to=settings.AUTH_USER_MODEL)),
                ('physical_room', models.ForeignKey(help_text='Target physical room unit being blocked', on_delete=django.db.models.deletion.CASCADE, related_name='room_blocks', to='rooms.physicalroom')),
            ],
            options={
                'verbose_name': 'Room Block',
                'verbose_name_plural': 'Room Blocks',
                'ordering': ['-start_date', 'physical_room__room_number'],
                'indexes': [models.Index(fields=['physical_room', 'is_active', 'start_date', 'end_date'], name='inventory_r_physica_8975b9_idx'), models.Index(fields=['start_date', 'end_date', 'is_active'], name='inventory_r_start_d_ad31c3_idx')],
            },
        ),
    ]
