# Generated by Django 5.2.17 on 2026-10-09 18:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('rooms', '0004_alter_roomimage_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StopSell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(db_index=True, help_text='Start date of stop-sell (inclusive)')),
                ('end_date', models.DateField(db_index=True, help_text='End date of stop-sell (exclusive checkout date)')),
                ('is_hotel_wide', models.BooleanField(db_index=True, default=True, help_text='If True, all room categories in the entire hotel are closed / marked sold out')),
                ('reason', models.CharField(default='Hotel Fully Booked', help_text='Reason for stop sell (e.g. Full House, Private Event, Renovation)', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Internal staff notes')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Status toggle. Inactive stop-sells do not block inventory')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Target category if stop-sell is category-specific', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stop_sells', to='rooms.roomcategory')),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff member who created the stop sell', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stop_sells', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stop Sell / Blackout',
                'verbose_name_plural': 'Stop Sells / Blackouts',
                'ordering': ['-start_date', '-created_at'],
                'indexes': [models.Index(fields=['start_date', 'end_date', 'is_active'], name='inventory_s_start_d_9b98c6_idx'), models.Index(fields=['is_hotel_wide', 'is_active', 'start_date', 'end_date'], name='inventory_s_is_hote_e041d3_idx')],
            },
        ),
    ]
