# Generated by Django 5.2.17 on 2026-09-30 18:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(help_text="URL-friendly identifier (e.g., 'ac-room', 'non-ac-room')", unique=True)),
                ('name', models.CharField(help_text="Display title of the room category (e.g., 'AC Room', 'Non-AC Room')", max_length=100)),
                ('tagline', models.CharField(blank=True, help_text='Short marketing summary tagline', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Comprehensive description of room features, fixtures, and layout')),
                ('included_adults', models.PositiveIntegerField(default=2, help_text='Number of adults included in base rate (typically 2)', validators=[django.core.validators.MinValueValidator(1)])),
                ('included_children', models.PositiveIntegerField(default=0, help_text='Number of children included in base rate (typically 0)')),
                ('max_adults', models.PositiveIntegerField(blank=True, help_text='Maximum adult capacity (optional ceiling; if null, capped by max_total_occupancy)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_children', models.PositiveIntegerField(blank=True, help_text='Maximum children capacity (optional ceiling)', null=True)),
                ('max_total_occupancy', models.PositiveIntegerField(default=4, help_text='Authoritative total PAX ceiling per room (AC: 4 PAX; Non-AC: 2 PAX baseline, 3 PAX pending confirmation)', validators=[django.core.validators.MinValueValidator(1)])),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Visual ordering sequence for frontend presentation')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this room category is active and visible for booking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Room Category',
                'verbose_name_plural': 'Room Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_number', models.CharField(db_index=True, help_text="Unique room door/unit number (e.g. '101', '102', '201')", max_length=20, unique=True)),
                ('floor', models.IntegerField(default=1, help_text='Floor number where the room is located')),
                ('operational_status', models.CharField(choices=[('operational', 'Operational / Ready'), ('maintenance', 'Under Maintenance'), ('blocked', 'Admin Blocked'), ('inactive', 'Inactive / Decommissioned')], db_index=True, default='operational', help_text='Current housekeeping / operational readiness status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal staff notes (maintenance history, physical quirks, amenities)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Flag indicating whether this physical unit is in active service')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Associated room category', on_delete=django.db.models.deletion.PROTECT, related_name='physical_rooms', to='rooms.roomcategory')),
            ],
            options={
                'verbose_name': 'Physical Room',
                'verbose_name_plural': 'Physical Rooms',
                'ordering': ['floor', 'room_number'],
                'indexes': [models.Index(fields=['category', 'operational_status', 'is_active'], name='rooms_physi_categor_1190a8_idx'), models.Index(fields=['operational_status', 'is_active'], name='rooms_physi_operati_a74998_idx')],
            },
        ),
    ]
