# Generated by Django 5.2.17 on 2026-09-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='physicalroom',
            name='rooms_physi_categor_1190a8_idx',
        ),
        migrations.RemoveIndex(
            model_name='physicalroom',
            name='rooms_physi_operati_a74998_idx',
        ),
        migrations.RemoveField(
            model_name='physicalroom',
            name='is_active',
        ),
        migrations.AddIndex(
            model_name='physicalroom',
            index=models.Index(fields=['category', 'operational_status'], name='rooms_physi_categor_8f90ab_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalroom',
            index=models.Index(fields=['operational_status'], name='rooms_physi_operati_66d60d_idx'),
        ),
    ]
