# Generated by Django 5.2.17 on 2026-09-30 18:55

import core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_remove_physicalroom_rooms_physi_categor_1190a8_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Name of the amenity (e.g. \'WAKEFIT Memory Foam Mattresses\', \'32" Smart TV\')', max_length=100, unique=True)),
                ('category', models.CharField(choices=[('comfort', 'Comfort'), ('convenience', 'Convenience'), ('safety', 'Safety & Security'), ('service', 'Hotel Service')], db_index=True, default='comfort', help_text='Amenity classification', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Detailed explanation of the amenity or service')),
                ('icon_name', models.CharField(default='check', help_text="Icon identifier for frontend rendering (e.g. 'wifi', 'tv', 'parking')", max_length=50)),
                ('is_property_wide', models.BooleanField(default=False, help_text='Flag indicating whether this amenity applies property-wide vs. specific room categories')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status toggle')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display ordering priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoomCategoryAmenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_highlight', models.BooleanField(default=False, help_text='Highlight this amenity prominently on category summary cards')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display priority for ordering within the category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_links', to='rooms.amenity')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_amenity_links', to='rooms.roomcategory')),
            ],
            options={
                'verbose_name': 'Room Category Amenity Link',
                'verbose_name_plural': 'Room Category Amenity Links',
                'ordering': ['display_order', 'amenity__name'],
            },
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='amenities',
            field=models.ManyToManyField(blank=True, help_text='Amenities associated with this room category', related_name='room_categories', through='rooms.RoomCategoryAmenity', to='rooms.amenity'),
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, help_text='Uploaded image file (JPEG, PNG, WebP up to 5MB)', null=True, upload_to='rooms/%Y/%m/', validators=[core.validators.validate_image_file])),
                ('image_url', models.URLField(blank=True, help_text='Optional external or CDN image URL', max_length=500)),
                ('caption', models.CharField(blank=True, help_text='Optional human-readable image caption', max_length=200)),
                ('alt_text', models.CharField(blank=True, help_text='Accessible alternative text description', max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Designates the primary hero image for the room category')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Sorting position in room gallery')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Visibility toggle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Associated room category', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.roomcategory')),
            ],
            options={
                'verbose_name': 'Room Image',
                'verbose_name_plural': 'Room Images',
                'ordering': ['display_order', '-is_primary', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='roomcategoryamenity',
            constraint=models.UniqueConstraint(fields=('category', 'amenity'), name='unique_category_amenity'),
        ),
        migrations.AddIndex(
            model_name='roomimage',
            index=models.Index(fields=['category', 'is_active', 'is_primary'], name='rooms_roomi_categor_af592a_idx'),
        ),
        migrations.AddConstraint(
            model_name='roomimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('category',), name='unique_primary_active_image_per_category'),
        ),
    ]
