# Generated by Django 5.2.17 on 2026-10-09 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_amenity_roomcategoryamenity_roomcategory_amenities_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomimage',
            options={'ordering': ['-is_primary', 'display_order', 'created_at'], 'verbose_name': 'Room Image', 'verbose_name_plural': 'Room Images'},
        ),
    ]
