# Generated by Django 5.2.17 on 2026-10-01 17:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0003_amenity_roomcategoryamenity_roomcategory_amenities_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_reference', models.CharField(db_index=True, editable=False, help_text='Customer-facing booking reference (e.g., MG-2026-X8K9M)', max_length=30, unique=True)),
                ('guest_name', models.CharField(help_text='Primary guest contact full name', max_length=150)),
                ('guest_phone', models.CharField(blank=True, help_text='Primary guest mobile phone number', max_length=20)),
                ('guest_email', models.EmailField(blank=True, help_text='Primary guest contact email address', max_length=254)),
                ('source', models.CharField(choices=[('website', 'Online Website Direct'), ('walk_in', 'Front Desk Walk-In'), ('phone', 'Phone Reservation'), ('whatsapp', 'WhatsApp Direct'), ('reception', 'Front Desk Offline'), ('corporate', 'Corporate Bulk Deal')], db_index=True, default='website', help_text='Booking origin channel', max_length=20)),
                ('status', models.CharField(choices=[('held', 'Temporary Hold (15 Min)'), ('confirmed', 'Confirmed Reservation'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled'), ('expired', 'Hold Expired'), ('no_show', 'No Show')], db_index=True, default='held', help_text='Current state in the booking lifecycle', max_length=20)),
                ('check_in_date', models.DateField(db_index=True, help_text='Scheduled arrival date (inclusive)')),
                ('check_out_date', models.DateField(db_index=True, help_text='Scheduled departure date (exclusive check-out date)')),
                ('total_adults', models.PositiveIntegerField(default=1, help_text='Total adult occupants across all booked rooms', validators=[django.core.validators.MinValueValidator(1)])),
                ('total_children', models.PositiveIntegerField(default=0, help_text='Total child occupants across all booked rooms')),
                ('hold_expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when temporary hold expires if unpaid', null=True)),
                ('special_requests', models.TextField(blank=True, help_text='Guest special requests submitted at booking time')),
                ('internal_notes', models.TextField(blank=True, help_text='Front desk and housekeeping operational notes')),
                ('is_overbooking', models.BooleanField(default=False, help_text='Flag indicating an authorized administrator capacity override')),
                ('overbooking_reason', models.TextField(blank=True, help_text='Mandatory justification note if overbooking was authorized')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff user who created the booking (null for direct customer web bookings)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, help_text='Authenticated customer account (null for anonymous/walk-in guests)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_quantity', models.PositiveIntegerField(default=1, help_text='Number of rooms of this category reserved in this booking line', validators=[django.core.validators.MinValueValidator(1)])),
                ('assigned_at', models.DateTimeField(blank=True, help_text='Timestamp when physical room was allocated', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Staff user who performed the physical room assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_booking_units', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(help_text='Parent booking reservation', on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='bookings.booking')),
                ('category', models.ForeignKey(help_text='Reserved accommodation category', on_delete=django.db.models.deletion.PROTECT, related_name='booked_rooms', to='rooms.roomcategory')),
                ('physical_room', models.ForeignKey(blank=True, help_text='Assigned physical room door unit (optional, assigned by reception)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_booking_rooms', to='rooms.physicalroom')),
            ],
            options={
                'verbose_name': 'Booked Room Item',
                'verbose_name_plural': 'Booked Room Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'check_in_date', 'check_out_date'], name='bookings_bo_status_cc152a_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer', 'status'], name='bookings_bo_custome_0cbf77_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['hold_expires_at', 'status'], name='bookings_bo_hold_ex_0add5a_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingroom',
            index=models.Index(fields=['booking', 'category'], name='bookings_bo_booking_ccf7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingroom',
            index=models.Index(fields=['physical_room'], name='bookings_bo_physica_fa5a93_idx'),
        ),
    ]
