# Generated by Django 5.2.17 on 2026-10-02 17:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='access_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Cryptographic unguessable access token for unauthenticated customer lookup and hold release'),
        ),
    ]
