# Generated by Django 5.2.17 on 2026-10-02 19:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingGuest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text='Full name of the stay guest', max_length=150)),
                ('guest_type', models.CharField(choices=[('adult', 'Adult'), ('child', 'Child')], default='adult', help_text='Classification as adult or child', max_length=10)),
                ('age', models.PositiveIntegerField(blank=True, help_text='Optional age in years', null=True)),
                ('phone', models.CharField(blank=True, help_text='Optional contact phone number', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Optional contact email address', max_length=254)),
                ('is_primary', models.BooleanField(default=False, help_text='Flag indicating whether this is the primary stay guest')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(help_text='Associated booking reservation', on_delete=django.db.models.deletion.CASCADE, related_name='guest_roster', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Stay Guest',
                'verbose_name_plural': 'Stay Guests',
                'ordering': ['-is_primary', 'created_at'],
                'indexes': [models.Index(fields=['booking', 'guest_type'], name='bookings_bo_booking_13ac0b_idx')],
            },
        ),
    ]
