# Generated by Django 5.2.17 on 2026-10-04 13:05

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bookingguest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Authoritative cancellation penalty / retention fee charged by hotel', max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_notes',
            field=models.TextField(blank=True, help_text='Additional guest notes or staff remarks regarding cancellation'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.CharField(blank=True, help_text='Guest-selected or staff-entered reason for booking cancellation', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_requested_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when cancellation request was submitted by guest', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when booking was formally cancelled', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, help_text='User (guest or staff) who authorized the cancellation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Authoritative refund amount eligible / approved for credit', max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_reference',
            field=models.CharField(blank=True, help_text='Razorpay refund ID (rfnd_XXXX) or bank transfer/UTR reference number', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_status',
            field=models.CharField(choices=[('not_applicable', 'Not Applicable'), ('pending', 'Pending Refund Approval'), ('processed', 'Refund Processed'), ('declined', 'Refund Declined / Non-refundable'), ('failed', 'Refund Gateway Failed')], db_index=True, default='not_applicable', help_text='Current state of monetary refund', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('held', 'Temporary Hold (15 Min)'), ('confirmed', 'Confirmed Reservation'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancellation_requested', 'Cancellation Requested'), ('refund_pending', 'Refund Pending'), ('cancelled', 'Cancelled'), ('refunded', 'Cancelled & Refunded'), ('expired', 'Hold Expired'), ('no_show', 'No Show')], db_index=True, default='held', help_text='Current state in the booking lifecycle', max_length=30),
        ),
    ]
