# Generated by Django 5.2.17 on 2026-10-04 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_cancellation_fee_booking_cancellation_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Cancellation & Refund Request',
                'verbose_name_plural': 'Cancellation & Refund Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bookings.booking',),
        ),
    ]
