# Generated by Django 5.2.17 on 2026-09-30 19:10

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0003_amenity_roomcategoryamenity_roomcategory_amenities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='GST', help_text="Name of the tax rule (e.g., 'GST (Accommodation)')", max_length=100)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Tax percentage or fixed amount (Confirmed baseline: 5.00%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('tax_type', models.CharField(choices=[('percentage', 'Percentage (%)'), ('fixed', 'Fixed Amount (INR)')], default='percentage', help_text='Method of tax calculation', max_length=20)),
                ('effective_from', models.DateField(blank=True, db_index=True, help_text='Start date for tax rule validity (null indicates unbounded start)', null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, help_text='End date for tax rule validity (null indicates valid indefinitely)', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Status toggle for this tax rule')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tax Rule',
                'verbose_name_plural': 'Tax Rules',
                'ordering': ['-is_active', '-effective_from', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'effective_from', 'effective_to'], name='pricing_tax_is_acti_d2c1f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoomRatePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Standard Tariff', help_text="Name of the rate plan (e.g., 'Standard Tariff', 'Seasonal Tariff', 'Corporate Rate')", max_length=100)),
                ('currency', models.CharField(default='INR', help_text='ISO 4217 Currency Code (default: INR)', max_length=3)),
                ('base_price_per_night', models.DecimalField(decimal_places=2, help_text='Base accommodation cost per night for included guest occupancy (AC: ₹1,599; Non-AC: ₹1,299)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('extra_adult_charge', models.DecimalField(decimal_places=2, default=Decimal('350.00'), help_text='Nightly charge per additional adult beyond included occupancy (Confirmed baseline: ₹350.00)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('extra_child_charge', models.DecimalField(decimal_places=2, default=Decimal('300.00'), help_text='Nightly charge per additional child beyond included occupancy (Confirmed baseline: ₹300.00)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('late_checkout_hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('150.00'), help_text='Hourly surcharge for late checkout up to 3 hours (AC: ₹150.00/hr; Non-AC: ₹100.00/hr)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('effective_from', models.DateField(blank=True, db_index=True, help_text='Start date for rate validity (null indicates unbounded start)', null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, help_text='End date for rate validity (null indicates active indefinitely)', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Status toggle for this rate plan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Associated room category', on_delete=django.db.models.deletion.PROTECT, related_name='rate_plans', to='rooms.roomcategory')),
            ],
            options={
                'verbose_name': 'Room Rate Plan',
                'verbose_name_plural': 'Room Rate Plans',
                'ordering': ['-is_active', '-effective_from', '-created_at'],
                'indexes': [models.Index(fields=['category', 'is_active', 'effective_from', 'effective_to'], name='pricing_roo_categor_0c8f68_idx')],
            },
        ),
    ]
