# Generated by Django 5.2.17 on 2026-10-02 18:47

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_access_token'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPriceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='INR', help_text='ISO 4217 Currency Code (default: INR)', max_length=3)),
                ('room_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total base room accommodation tariff before extra guests, surcharges, and taxes', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('extra_guest_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total surcharges for extra adult and child occupants beyond included occupancy', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('late_checkout_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total hourly late checkout charges', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('miscellaneous_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Other authorized charges or surcharges', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Authorized discount amount deducted from taxable subtotal', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('taxable_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total taxable accommodation amount (Room + Extra Guests + Late Checkout + Misc - Discount)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_rule_name', models.CharField(default='GST', help_text="Name of the applied tax rule (e.g., 'GST (Accommodation 5%)')", max_length=100)),
                ('tax_rate_percent', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Tax percentage applied', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated tax amount (e.g., GST 5%)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('gross_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Authoritative total payable amount (Taxable Subtotal + Tax Amount)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('advance_amount_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='50% advance deposit due online via Razorpay', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('balance_amount_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Remaining 50% balance payable at front desk prior to room key handover', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('itemized_breakdown', models.JSONField(blank=True, default=dict, help_text='Complete structured breakdown of nightly rates, occupancy, surcharges, and tax calculations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(help_text='Associated booking reservation', on_delete=django.db.models.deletion.CASCADE, related_name='price_snapshot', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Booking Price Snapshot',
                'verbose_name_plural': 'Booking Price Snapshots',
                'ordering': ['-created_at'],
            },
        ),
    ]
