# Generated by Django 5.2.17 on 2026-09-30 18:55

import core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title or label for the photo/media item', max_length=150)),
                ('category', models.CharField(choices=[('rooms', 'Guest Rooms'), ('property', 'Hotel Property'), ('amenities', 'Amenities'), ('exterior', 'Building & Reception')], db_index=True, default='property', help_text='Gallery category classification', max_length=30)),
                ('image', models.ImageField(blank=True, help_text='Uploaded media file (JPEG, PNG, WebP up to 5MB)', null=True, upload_to='gallery/%Y/%m/', validators=[core.validators.validate_image_file])),
                ('image_url', models.URLField(blank=True, help_text='Optional external or CDN image URL', max_length=500)),
                ('caption', models.CharField(blank=True, help_text='Optional descriptive caption', max_length=255)),
                ('alt_text', models.CharField(blank=True, help_text='Accessible alternative text description', max_length=200)),
                ('is_featured', models.BooleanField(default=False, help_text='Flag indicating whether to showcase this item on the home page gallery preview')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Visual ordering sequence')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Publication status toggle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery Media',
                'verbose_name_plural': 'Gallery Media Items',
                'ordering': ['display_order', '-is_featured', '-created_at'],
                'indexes': [models.Index(fields=['category', 'is_active', 'display_order'], name='cms_gallery_categor_640029_idx')],
            },
        ),
    ]
