# Generated by Django 5.2.17 on 2026-09-30 19:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('00000000-0000-0000-0000-000000000001'), editable=False, primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(default='Manohar Grand', help_text='Official business/property name', max_length=150)),
                ('primary_phone', models.CharField(blank=True, help_text='Primary reception / contact phone number', max_length=20)),
                ('secondary_phone', models.CharField(blank=True, help_text='Secondary reception / support phone number', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Official contact email address', max_length=254)),
                ('address', models.TextField(blank=True, help_text='Full physical hotel street address')),
                ('near_landmark', models.CharField(blank=True, help_text='Prominent nearby landmark', max_length=150)),
                ('google_maps_url', models.URLField(blank=True, help_text='Customer-facing Google Maps link', max_length=500)),
                ('google_maps_embed_url', models.URLField(blank=True, help_text='Google Maps iframe embed URL for frontend rendering', max_length=1000)),
                ('standard_check_in_time', models.TimeField(default='11:00:00', help_text='Standard guest check-in time (Confirmed baseline: 11:00 AM)')),
                ('standard_check_out_time', models.TimeField(default='11:00:00', help_text='Standard guest check-out time (Confirmed baseline: 11:00 AM next day)')),
                ('max_late_checkout_hours', models.PositiveIntegerField(default=3, help_text='Maximum permissible late check-out window in hours (Confirmed baseline: 3 hours)')),
                ('cancellation_policy_text', models.TextField(default='Once booking/payment is confirmed, booking cannot be cancelled/refunded.', help_text='Official guest cancellation policy statement')),
                ('guest_id_policy_text', models.TextField(blank=True, help_text='Mandatory guest photo identification and Aadhaar requirements')),
                ('age_policy_text', models.TextField(blank=True, help_text='Primary guest minimum age requirements')),
                ('is_active', models.BooleanField(default=True, help_text='Active configuration status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hotel Configuration',
                'verbose_name_plural': 'Hotel Configuration',
            },
        ),
    ]
