# Generated by Django 5.2.17 on 2026-10-01 16:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_hotelconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_key', models.SlugField(help_text="Unique identifier for the section (e.g., 'hero', 'welcome', 'why-choose-us', 'about', 'contact')", unique=True)),
                ('title', models.CharField(help_text='Primary headline or section title', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Optional secondary subtitle or tagline', max_length=255)),
                ('body', models.TextField(blank=True, help_text='Main descriptive body text (plain text or structured markdown)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Structured JSON attributes (e.g. CTA button texts, highlight items, badges)')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Visual ordering sequence for page presentation')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Publication toggle for this content section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CMS Section',
                'verbose_name_plural': 'CMS Sections',
                'ordering': ['display_order', 'section_key'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(help_text='The question prompt asked by visitors/guests', max_length=255)),
                ('answer', models.TextField(help_text='Authoritative answer text')),
                ('category', models.CharField(choices=[('general', 'General Hotel Info'), ('booking', 'Reservations & Booking'), ('checkin_checkout', 'Check-in & Check-out'), ('amenities', 'Amenities & Services'), ('cancellation_refunds', 'Cancellation & Non-Refund Policy'), ('location', 'Location & Connectivity')], db_index=True, default='general', help_text='Classification for accordion grouping on the frontend', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Visual sorting sequence within category')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Publication toggle for this FAQ item')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ Item',
                'verbose_name_plural': 'FAQ Items',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
