# Generated by Django 5.2.17 on 2026-10-03 07:55

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_bookingguest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal unique payment order identifier', primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('advance', '50% Advance Deposit'), ('balance', 'Remaining Balance'), ('full', 'Full Stay Payment')], db_index=True, default='advance', help_text='Payment phase / purpose (advance, balance, full)', max_length=20)),
                ('currency', models.CharField(default='INR', help_text='Three-letter ISO currency code (default INR)', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payable amount in standard currency units (INR)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('amount_paise', models.PositiveBigIntegerField(help_text='Payable amount in integer paise sent to Razorpay (amount * 100)')),
                ('razorpay_order_id', models.CharField(db_index=True, help_text='Authoritative Razorpay gateway order identifier (order_XXXXX)', max_length=100, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, help_text='Razorpay payment identifier populated after customer payment execution (pay_XXXXX)', max_length=100)),
                ('razorpay_signature', models.CharField(blank=True, help_text='Cryptographic payment signature verified via HMAC-SHA256', max_length=255)),
                ('status', models.CharField(choices=[('created', 'Created'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], db_index=True, default='created', help_text='Current payment order status in gateway lifecycle', max_length=20)),
                ('provider', models.CharField(default='razorpay', help_text='Payment gateway provider name', max_length=30)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, help_text='Client or server idempotency key preventing duplicate gateway order generation', max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Provider payload metadata, notes, and diagnostic context')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(help_text='Target reservation associated with this payment order', on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Payment Order',
                'verbose_name_plural': 'Payment Orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking', 'purpose', 'status'], name='payments_pa_booking_4f2286_idx')],
            },
        ),
    ]
