# Generated by Django 5.2.17 on 2026-10-03 08:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(db_index=True, default='razorpay', max_length=30)),
                ('event_id', models.CharField(db_index=True, help_text='Gateway unique event identifier (e.g., evt_XXXXX)', max_length=100)),
                ('event_type', models.CharField(db_index=True, help_text='Gateway event name (e.g., payment.captured, payment.failed)', max_length=100)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], db_index=True, default='received', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Sanitized webhook payload content')),
                ('error_message', models.TextField(blank=True, help_text='Diagnostic failure error details if processing failed')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Webhook Event Log',
                'verbose_name_plural': 'Webhook Event Logs',
                'ordering': ['-received_at'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_id'), name='unique_provider_event_id')],
            },
        ),
    ]
