# Generated by Django 5.2.17 on 2026-09-30 18:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_email', models.EmailField(blank=True, help_text='Snapshot of actor email at the time of action', max_length=254)),
                ('actor_role', models.CharField(blank=True, help_text='Snapshot of actor staff role at the time of action', max_length=50)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('status_change', 'Status Changed'), ('price_change', 'Price Modified'), ('config_change', 'Config Modified'), ('override', 'Admin Override')], db_index=True, max_length=50)),
                ('resource_type', models.CharField(db_index=True, help_text="Model/Entity class name (e.g., 'RoomCategory', 'PhysicalRoom')", max_length=100)),
                ('resource_id', models.CharField(db_index=True, help_text='Primary key identifier of the modified resource', max_length=100)),
                ('old_values', models.JSONField(blank=True, default=dict, help_text='JSON snapshot of field values prior to modification')),
                ('new_values', models.JSONField(blank=True, default=dict, help_text='JSON snapshot of field values after modification')),
                ('reason', models.TextField(blank=True, help_text='Optional human-readable justification for the change')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address initiating the request', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action (null for system automated tasks)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log Entries',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['resource_type', 'resource_id'], name='core_auditl_resourc_a674ad_idx'), models.Index(fields=['actor', 'timestamp'], name='core_auditl_actor_i_19c60f_idx')],
            },
        ),
    ]
